import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#16130b",
        surface: "#16130b",
        "surface-dim": "#16130b",
        "surface-bright": "#3d392f",
        "surface-container-lowest": "#110e07",
        "surface-container-low": "#1f1b13",
        "surface-container": "#231f17",
        "surface-container-high": "#2d2a21",
        "surface-container-highest": "#38342b",
        "surface-variant": "#38342b",
        primary: "#f2ca50",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "primary-container": "#d4af37",
        "on-primary": "#3c2f00",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "on-primary-container": "#554300",
        "inverse-primary": "#735c00",
        secondary: "#c6c7c2",
        "secondary-fixed": "#e3e3de",
        "secondary-fixed-dim": "#c6c7c2",
        "secondary-container": "#484a46",
        "on-secondary": "#2f312e",
        "on-secondary-fixed": "#1a1c19",
        "on-secondary-fixed-variant": "#454744",
        "on-secondary-container": "#b8b9b4",
        "on-background": "#eae1d4",
        "on-surface": "#eae1d4",
        "on-surface-variant": "#d0c5af",
        outline: "#99907c",
        "outline-variant": "#4d4635",
        "surface-tint": "#e9c349",
        "inverse-surface": "#eae1d4",
        "inverse-on-surface": "#343027",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        tertiary: "#bfcdff",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#97b0ff",
        "on-tertiary": "#082b72",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#27438a",
        "on-tertiary-container": "#254188",
      },
      fontFamily: {
        serif: ["Noto Serif", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-margin": "20px",
        gutter: "16px",
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "pulse-gold": { "0%, 100%": { boxShadow: "0 0 0 0 rgba(212,175,55,0)" }, "50%": { boxShadow: "0 0 0 6px rgba(212,175,55,0.15)" } },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        shimmer: "shimmer 2s infinite linear",
        "pulse-gold": "pulse-gold 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
